### ISSUE TITLE
[help]安装后，第一次使用，报这个错是什么问题？感谢回复

### ISSUE THREAD

**Issue by s2wcn** [Ascotbe/Medusa#23]
s2wcn@debian:~/Medusa$ sudo python3 MedusaScan.py -u https://www.ascotbe.com
Traceback (most recent call last):
  File "MedusaScan.py", line 3, in <module>
    from Modules.Confluence import Confluence
  File "/home/s2wcn/Medusa/Modules/Confluence/Confluence.py", line 3, in <module>
    from Modules.Confluence import AtlassianConfluencePathTraversalAndCommandExecutionVulnerability
  File "/home/s2wcn/Medusa/Modules/Confluence/AtlassianConfluencePathTraversalAndCommandExecutionVulnerability.py", line 5, in <module>
    import ClassCongregation
  File "/home/s2wcn/Medusa/ClassCongregation.py", line 3, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by Ascotbe** [comment]
装这个fake_useragent包如果不会请百度，有具体方法
