### ISSUE TITLE
[help]又是一个错误

### ISSUE THREAD

**Issue by s2wcn** [Ascotbe/Medusa#24]
s2wcn@debian:~/Medusa$ sudo python3 MedusaScan.py -u https://www.ascotbe.com
Traceback (most recent call last):
  File "MedusaScan.py", line 17, in <module>
    from Modules.Dubbo import Dubbo
  File "/home/s2wcn/Medusa/Modules/Dubbo/Dubbo.py", line 3, in <module>
    from Modules.Dubbo import DubboProviderDefaultAntiSequenceVulnerability
  File "/home/s2wcn/Medusa/Modules/Dubbo/DubboProviderDefaultAntiSequenceVulnerability.py", line 7, in <module>
    from dubbo.codec.hessian2 import new_object
ModuleNotFoundError: No module named 'dubbo'

s2wcn@debian:~/Medusa$ pip3 install dubbo
Collecting dubbo
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/dubbo/

**Comment by s2wcn** [comment]
s2wcn@debian:~/Medusa$ pip3 install dubbo-py
Requirement already satisfied: dubbo-py in /home/s2wcn/.local/lib/python3.7/site-packages (0.2.2)
Requirement already satisfied: kazoo in /home/s2wcn/.local/lib/python3.7/site-packages (from dubbo-py) (2.8.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from kazoo->dubbo-py) (1.12.0)

**Comment by s2wcn** [comment]
问题，还是没解决啊

**Comment by s2wcn** [comment]
安装提示都有，但是使用，还是提示
ModuleNotFoundError: No module named 'dubbo'

**Comment by s2wcn** [comment]
s2wcn@debian:~/Medusa$ pip3 install dubbo-py
Requirement already satisfied: dubbo-py in /home/s2wcn/.local/lib/python3.7/site-packages (0.2.2)
Requirement already satisfied: kazoo in /home/s2wcn/.local/lib/python3.7/site-packages (from dubbo-py) (2.8.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from kazoo->dubbo-py) (1.12.0)
s2wcn@debian:~/Medusa$ sudo python3 MedusaScan.py -u https://www.ascotbe.com
[sudo] s2wcn 的密码：
Traceback (most recent call last):
  File "MedusaScan.py", line 17, in <module>
    from Modules.Dubbo import Dubbo
  File "/home/s2wcn/Medusa/Modules/Dubbo/Dubbo.py", line 3, in <module>
    from Modules.Dubbo import DubboProviderDefaultAntiSequenceVulnerability
  File "/home/s2wcn/Medusa/Modules/Dubbo/DubboProviderDefaultAntiSequenceVulnerability.py", line 7, in <module>
    from dubbo.codec.hessian2 import new_object
ModuleNotFoundError: No module named 'dubbo'
