### ISSUE TITLE
使用命令  python3 MedusaScan.py -f -test.txt -PR 1-65535 扫描端口 报错

### ISSUE THREAD

**Issue by wikipurse** [Ascotbe/Medusa#29]
使用命令  python3 MedusaScan.py -f -test.txt -PR 1-65535 扫描端口 报错
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "MedusaScan.py", line 150, in Port
    ClassCongregation.PortScan(Url).Start(**kwargs)
  File "/root/Medusa/ClassCongregation.py", line 129, in Start
    for Port in self.CustomizePortList:
AttributeError: 'PortScan' object has no attribute 'CustomizePortList'
那个pip3 install -r Medusa.txt 安装时候没有报错 nmap 也安装了

**Comment by wikipurse** [comment]
test.txt 放的是ip地址不是url地址

**Comment by Ascotbe** [comment]
系统版本，还有报错日志我看下，麻烦以后提问题按格式来

**Comment by Ascotbe** [comment]
已更新[v0.91.1](https://github.com/Ascotbe/Medusa/commit/aeb22613ce0a43d47575025a5cf6a37da9ab13fe)
